BUTTON_PUBLISH = "//button[text()='Опубликовать']"
CATEGORY_OPTION = "//span[text()='{}']"
CITY_OPTION = "//span[text()='{}']"
DROPDOWN_CATEGORY = "//input[@name='category']/following-sibling::button"
DROPDOWN_CITY = "//input[@name='city']/following-sibling::button"
FIELD_NAME = "//input[@placeholder='Название']"
FIELD_DESCRIPTION = "//textarea[@placeholder='Описание товара']"
FIELD_PRICE = "//input[@placeholder='Стоимость']"
MODAL_TITLE_AUTH_REQUIRED = "//h1[contains(text(), 'Чтобы разместить объявление, авторизуйтесь')]"
MY_ADS_BLOCK = "//h1[contains(text(), 'Мои объявления')]"
MY_AD_HEADER = "//h2[text()='{}']"
PROFILE_LINK = "//button[@class='circleSmall']"
RADIO_CONDITION_NEW = "//input[@name='condition' and @value='Новый']/following-sibling::div"
RADIO_CONDITION_USED = "//input[@name='condition' and @value='Б/У']/following-sibling::div"